#include "mainwindow.h"
#include "ui_mainwindow.h"   // generated by AUTOUIC

MainWindow::MainWindow(QWidget *parent)
  : QMainWindow(parent),
    ui(new Ui::MainWindow)
{
  ui->setupUi(this);

  initializeMainMenu();
  initializeMenuBar();
  initializeApp();
  initializeStack();

  connectMainMenu();
  connectApp();
}

MainWindow::~MainWindow()
{
  delete ui;
}

void MainWindow::initializeMainMenu()
{
  menu = new MainMenu(this);
  menu->addButton("start");
  menu->addButton("info");
  menu->addButton("exit");
  menu->show();
}

void MainWindow::initializeStack()
{
  stack = new QStackedWidget(this);
  stack->addWidget(menu);
  stack->addWidget(app);
  stack->setCurrentIndex(0);
  this->setCentralWidget(stack);
}

// Need work
void MainWindow::initializeMenuBar()
{
  // ...
  menuBar()->hide();
}

// Need work
void MainWindow::initializeApp()
{
  app = new QWidget(this);
  // ...
}


void MainWindow::connectMainMenu()
{
  QVector<QPushButton*>& b = menu->getButtons();
  connect(b[0], &QPushButton::clicked, this, &MainWindow::slotChangeWindow);
}

void MainWindow::slotChangeWindow()
{
  stack->setCurrentIndex(1);
}

// Need work
void MainWindow::connectApp()
{
  // ...
}